######################
# configuration file #
######################
---

CPUs: 40
number_dim: 6

dir_data: "../data"

############################## GetData #############################################

file_annotation: "../data/annotation_SGD.tsv"

data_transcriptome_list:
  - microarray 
  - MUREN_log_YMC2014 
  - transcriptome_concatenate

data_histone_list:
  - H3K4me3
  - H3K9ac
  - H3K14ac
  - H3K18ac
  - H3K36me3
  - H3K56ac
  - H4K5ac
  - H4K16ac

data_metabolome_list:
  - Metabolite_gc
  - Metabolite_lc
  - Metabolite_interpolated_gc
  - Metabolite_interpolated_lc



############################## Enrichment ######################################

pathway_database_dir: "../data/pathway_database_20230530"

enrichment:
  signif_level: 0.05
  GO:
    minGeneNum: 1
    maxGeneNum: .inf
  minCommonGeneNum: 5
  maxCommonGeneNum: 1000
  


